### ISSUE TITLE
Implement Permissions support

### ISSUE THREAD

**Issue by niftymonkey** [niftymonkey/NiftyWarp#5]
Need to implement support of Permissions for the commands in this plugin.

Permissions Thread:  http://forums.bukkit.org/threads/admn-dev-permissions-3-1-5b-the-plugin-of-tomorrow-818.18430/
How to hook into Permissions:  https://github.com/TheYeti/Permissions/wiki/API-Reference

**Comment by Cybernaught** [comment]
First pass checked in.  Had a harsh 3-way merge to work through.
